### ISSUE TITLE
Topology questions

### ISSUE THREAD

**Issue by paxinos** [ElGranLoky/node-red-contrib-amqp-ack#4]
We plan on having multiple instances of a flow.  Is there a way to specify a queue to have a instance specific name in a topology configuration?   In other words, if we don't specify the topology we get a unique name automatically generated.  

As we are using topic exchanges we need to set the 'pattern'.  So it seems we need to set the topology.

Or is there a way to set the RoutingKey (pattern) in the Input Node configuration without using Topology?   We've tried but that binding does not appear in rabbitmq...

**Comment by ElGranLoky** [comment]
1.- You can send to the node **msg.readFrom** to received dynamically the name of the queue or exchange that will be read.

2.- Example with topology:

`[{"id":"46a86327.56769c","type":"tab","label":"Rabbit Topology","disabled":false,"info":""},{"id":"3b7da0b2.c16dc","type":"inject","z":"46a86327.56769c","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"1","crontab":"","once":false,"onceDelay":0.1,"topic":"1","payload":"","payloadType":"date","x":120,"y":40,"wires":[["b018c66f.937c88"]]},{"id":"b018c66f.937c88","type":"amqp out","z":"46a86327.56769c","name":"exchange1","routingkey":"","iotype":"0","ioname":"exchange1","server":"24c0b0e4.35927","x":360,"y":40,"wires":[]},{"id":"7cbec4e1.4917cc","type":"amqp in","z":"46a86327.56769c","name":"","topic":"","iotype":"4","ioname":"queue1","server":"24c0b0e4.35927","x":280,"y":210,"wires":[["b6e593cf.239f3"]]},{"id":"38d952fc.3a697e","type":"debug","z":"46a86327.56769c","name":"Error & 1","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":440,"y":260,"wires":[]},{"id":"1f80ba92.29db85","type":"inject","z":"46a86327.56769c","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"2","crontab":"","once":false,"onceDelay":0.1,"topic":"error","payload":"","payloadType":"date","x":130,"y":80,"wires":[["b018c66f.937c88"]]},{"id":"30357524.ff9bfa","type":"inject","z":"46a86327.56769c","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"1","crontab":"","once":false,"onceDelay":0.1,"topic":"debug","payload":"","payloadType":"date","x":130,"y":120,"wires":[["b018c66f.937c88"]]},{"id":"253b7d79.24a772","type":"inject","z":"46a86327.56769c","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":true,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":110,"y":210,"wires":[["7cbec4e1.4917cc"]]},{"id":"a44ae0d9.2726a","type":"amqp in","z":"46a86327.56769c","name":"","topic":"","iotype":"4","ioname":"queue2","server":"24c0b0e4.35927","x":280,"y":260,"wires":[["38d952fc.3a697e"]]},{"id":"b549b541.334828","type":"inject","z":"46a86327.56769c","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":true,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":110,"y":260,"wires":[["a44ae0d9.2726a"]]},{"id":"b6e593cf.239f3","type":"debug","z":"46a86327.56769c","name":"Debug","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":430,"y":210,"wires":[]},{"id":"24c0b0e4.35927","type":"amqp-server","host":"iphost","port":"5672","vhost":"","keepalive":"30","usetls":false,"verifyservercert":true,"useca":false,"ca":"","usetopology":true,"topology":"{\n\t\"exchanges\": [\n\t\t{\"name\": \"exchange1\", \"options\": {\"durable\": false}},\n\t\t{\"name\": \"exchange2\"}\n\t],\n\t\"queues\": [\n\t\t{\"name\": \"queue1\", \"options\": {\"messageTtl\": 60000}},\n\t\t{\"name\": \"queue2\"}\n\t],\n\t\"bindings\": [\n\t\t{\"source\": \"exchange1\", \"queue\": \"queue1\", \"pattern\": \"debug\", \"args\": {}},\n\t\t{\"source\": \"exchange1\", \"exchange\": \"exchange2\", \"pattern\": \"error\"},\n\t\t{\"source\": \"exchange2\", \"queue\": \"queue2\", \"pattern\": \"error\"},\n\t\t{\"source\": \"exchange1\", \"queue\": \"queue2\", \"pattern\": \"1\"}\n\t]\n}","prefetch":false,"prefetchvalue":"20","prefetchack":true,"prefetchvalueack":"30"}]`

If it is the answer to the question, tell me to close the issue.

**Comment by paxinos** [comment]
We are getting
"AMQP input error: amqp-ts Queue.activateConsumer error: consumer already defined"
With that flow.

Is there a way to dynamically create the topology?

**Comment by paxinos** [comment]
What would be ideal - at least for us - 
Specify the Exchange (topic in our case)
Specify the routingKey we want to listen 
The node would dynamically create the queue and bind it to the exchange.
I do like your concept of msg.readFrom.  Perhaps extend that to be able to change the routingKey we are listening to.

**Comment by ElGranLoky** [comment]
Yes & No.

I don't know how to make the server nodes have dynamic topologies and I don't think it would be correct to do so either.

Let me explain, you can create several server nodes each with a defined topology even if they point to the same rabbit server. And depending on the message, send it to one node or another to create the topology, but a topology must not be dynamic, otherwise the process will not be well defined.

Regarding the RoutingKey, use the topic of the message and you can make it change for each message.

![image](https://user-images.githubusercontent.com/2712200/106366411-018ae700-633c-11eb-84ac-5a7ac292f3f0.png)

From https://www.rabbitmq.com/tutorials/tutorial-five-python.html:


Topic exchange
Messages sent to a **topic exchange can't have an arbitrary routing_key - it must be a list of words**, delimited by dots. The words can be anything, but usually they specify some features connected to the message. A few valid routing key examples: "stock.usd.nyse", "nyse.vmw", "quick.orange.rabbit". There can be as many words in the routing key as you like, up to the limit of 255 bytes.

After you can connect to the queue to get the routingkey and switch as you need.

Example:

[{"id":"3b7da0b2.c16dc","type":"inject","z":"46a86327.56769c","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"10","crontab":"","once":false,"onceDelay":0.1,"topic":"error.1","payload":"error1","payloadType":"str","x":120,"y":40,"wires":[["b018c66f.937c88"]]},{"id":"b018c66f.937c88","type":"amqp out","z":"46a86327.56769c","name":"topic1","routingkey":"","iotype":"3","ioname":"topic1","server":"1e05f36b.6da42d","x":400,"y":40,"wires":[]},{"id":"7cbec4e1.4917cc","type":"amqp in","z":"46a86327.56769c","name":"","topic":"","iotype":"4","ioname":"debug","server":"1e05f36b.6da42d","x":280,"y":210,"wires":[["b6e593cf.239f3"]]},{"id":"38d952fc.3a697e","type":"debug","z":"46a86327.56769c","name":"Error","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":450,"y":260,"wires":[]},{"id":"1f80ba92.29db85","type":"inject","z":"46a86327.56769c","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"10","crontab":"","once":false,"onceDelay":0.1,"topic":"error.2","payload":"error2","payloadType":"str","x":120,"y":160,"wires":[["f14ce5ab.c18238"]]},{"id":"30357524.ff9bfa","type":"inject","z":"46a86327.56769c","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"10","crontab":"","once":false,"onceDelay":0.1,"topic":"debug.1","payload":"debug1","payloadType":"str","x":130,"y":80,"wires":[["b018c66f.937c88","f14ce5ab.c18238"]]},{"id":"253b7d79.24a772","type":"inject","z":"46a86327.56769c","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":true,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":110,"y":210,"wires":[["7cbec4e1.4917cc"]]},{"id":"a44ae0d9.2726a","type":"amqp in","z":"46a86327.56769c","name":"","topic":"error","iotype":"4","ioname":"error","server":"1e05f36b.6da42d","x":280,"y":260,"wires":[["38d952fc.3a697e"]]},{"id":"b549b541.334828","type":"inject","z":"46a86327.56769c","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":true,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":110,"y":260,"wires":[["a44ae0d9.2726a"]]},{"id":"b6e593cf.239f3","type":"debug","z":"46a86327.56769c","name":"Debug","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":450,"y":210,"wires":[]},{"id":"f14ce5ab.c18238","type":"amqp out","z":"46a86327.56769c","name":"topic2","routingkey":"","iotype":"3","ioname":"topic2","server":"2f60a6d1.333c1a","x":400,"y":110,"wires":[]},{"id":"63e06e77.868","type":"inject","z":"46a86327.56769c","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"10","crontab":"","once":false,"onceDelay":0.1,"topic":"debug.2","payload":"debug2","payloadType":"str","x":130,"y":120,"wires":[["f14ce5ab.c18238"]]},{"id":"1e05f36b.6da42d","type":"amqp-server","host":"iphost1","port":"5672","vhost":"","keepalive":"30","usetls":false,"verifyservercert":true,"useca":false,"ca":"","usetopology":true,"topology":"{\n\t\"exchanges\": [\n\t\t{\"name\": \"topic1\", \"type\": \"topic\"}\n\t],\n\t\"queues\": [\n\t\t{\"name\": \"error\"}\n\t],\n\t\"bindings\": [\n\t\t{\"source\": \"topic1\", \"queue\": \"error\", \"pattern\": \"error.*\", \"args\": {}},\n\t\t{\"source\": \"topic1\", \"queue\": \"debug\", \"pattern\": \"debug.*\"}\n\t]\n}","prefetch":false,"prefetchvalue":"1","prefetchack":false,"prefetchvalueack":"10"},{"id":"2f60a6d1.333c1a","type":"amqp-server","host":"iphost2","port":"5672","vhost":"","keepalive":"30","usetls":false,"verifyservercert":true,"useca":false,"ca":"","usetopology":true,"topology":"{\n\t\"exchanges\": [\n\t\t{\"name\": \"topic2\", \"type\": \"topic\"}\n\t],\n\t\"queues\": [\n\t\t{\"name\": \"error\"},\n\t\t{\"name\": \"debug\"}\n\t],\n\t\"bindings\": [\n\t\t{\"source\": \"topic2\", \"queue\": \"debug\", \"pattern\": \"debug.*\"}\n\t]\n}","prefetch":false,"prefetchvalue":"1","prefetchack":false,"prefetchvalueack":"10"}]

Exchange - Topic2 - discard all the error messages.

Sorry if I dont understand.

**Comment by ElGranLoky** [comment]
The repository is deprecated.

As an alternative you can use [@meowwolf/node-red-contrib-amqp](https://flows.nodered.org/node/@meowwolf/node-red-contrib-amqp)
